# Generated by Django 5.2.13 on 2026-05-04 11:25

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Domaine',
                'verbose_name_plural': 'Domaines',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='drp/pieces/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('cloturee', 'Clôturée')], default='en_cours', max_length=20)),
                ('poids_prix', models.PositiveSmallIntegerField(default=50, help_text='Pondération du critère prix (1–100).', validators=[django.core.validators.MinValueValidator(1)])),
                ('poids_delai', models.PositiveSmallIntegerField(default=50, help_text='Pondération du critère délai (1–100).', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drps_creees', to=settings.AUTH_USER_MODEL)),
                ('domaines', models.ManyToManyField(related_name='drps', to='drp.domaine')),
            ],
            options={
                'verbose_name': 'DRP',
                'verbose_name_plural': 'DRP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=40)),
                ('actif', models.BooleanField(default=True)),
                ('domaines', models.ManyToManyField(blank=True, related_name='fournisseurs', to='drp.domaine')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expiration', models.DateTimeField()),
                ('statut', models.CharField(choices=[('envoyee', 'Envoyée'), ('repondue', 'Répondue'), ('expiree', 'Expirée')], default='envoyee', max_length=20)),
                ('drp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='drp.drp')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='drp.fournisseur')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'ordering': ['drp', 'fournisseur'],
            },
        ),
        migrations.AddField(
            model_name='drp',
            name='selected_invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drps_retenues', to='drp.invitation'),
        ),
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('delai_jours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('commentaire', models.TextField(blank=True)),
                ('fichier', models.FileField(upload_to='proformas/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('score', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proforma', to='drp.invitation')),
            ],
            options={
                'verbose_name': 'Proforma',
                'verbose_name_plural': 'Proformas',
            },
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('fournisseur', 'drp'), name='unique_invitation_fournisseur_drp'),
        ),
    ]
