# Generated by Django 5.2.13 on 2026-05-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drp', '0003_responsable_achat_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drp',
            name='date_cloture',
            field=models.DateTimeField(help_text='Les fournisseurs ne peuvent plus soumettre de proforma après cette date.', verbose_name='Date de clôture'),
        ),
        migrations.AlterField(
            model_name='drp',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('cloturee', 'Clôturée'), ('annulee', 'Annulée')], default='en_cours', max_length=20),
        ),
    ]
