# Generated by Django 5.2.14 on 2026-05-21 15:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drp', '0007_add_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='drp',
            name='budget_previsionnel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Budget prévisionnel (FCFA)'),
        ),
    ]
