# Generated by Django 4.2.17 on 2026-06-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drp', '0008_add_budget_previsionnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='date_reactivation',
            field=models.DateTimeField(blank=True, help_text="Si renseigné, le lien reste valide jusqu'à cette date même après la clôture du DRP.", null=True, verbose_name="Réactivé jusqu'au"),
        ),
    ]
